# Sklearn

## sklearn.model_selection

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
from sklearn import model_selection, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [2]:
iris = datasets.load_iris()

In [13]:
iris.

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [14]:
iris.keys()

['target', 'DESCR', 'target_names', 'feature_names', 'data', 'filename']

In [3]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [4]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [5]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [6]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[5.  3.6 1.4 0.2]
 [4.8 3.4 1.9 0.2]
 [6.3 2.3 4.4 1.3]
 [4.9 3.1 1.5 0.1]
 [6.8 3.2 5.9 2.3]]


Тестовая выборка:
[[7.7 2.8 6.7 2. ]
 [5.1 2.5 3.  1.1]
 [6.2 3.4 5.4 2.3]
 [4.4 3.  1.3 0.2]
 [5.9 3.2 4.8 1.8]]


In [15]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[0 0 1 0 2 0 0 2 0 0 1 1 0 2 0 2 0 1 1 1 1 2 2 0 1 2 2 1 0 1 2 0 0 2 0 0 0
 0 1 2 2 2 0 1 1 2 0 2 2 1 1 2 1 2 1 2 2 1 0 0 2 1 0 2 1 1 0 0 1 1 2 1 0 2
 1 2 0 1 0 2 0 1 2 2 0 1 0 2 0 0 2 1 2 0 0 0 1 1 0 0 2 0 1 1 2]


Метки классов на тестовой выборке:
[2 1 2 0 1 0 1 2 2 2 0 2 1 2 2 0 1 1 0 2 1 0 2 2 2 2 1 1 1 0 0 0 1 1 1 1 0
 1 1 2 2 0 1 2 2]


### Стратегии проведения кросс-валидации

In [16]:
#сгенерируем короткое подобие датасета, где элементы совпадают с порядковым номером
X = range(0,10)

#### KFold

In [17]:
kf = model_selection.KFold(n_splits = 5)
for train_indices, test_indices in kf.split(X):
    print train_indices, test_indices

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [19]:
kf = model_selection.KFold(n_splits = 2, shuffle = True)
for train_indices, test_indices in kf.split(X):
    print train_indices, test_indices

[1 4 5 6 8] [0 2 3 7 9]
[0 2 3 7 9] [1 4 5 6 8]


In [26]:
kf = model_selection.KFold(n_splits = 2, shuffle = True, random_state = 1)
for train_indices, test_indices in kf.split(X):
    print train_indices, test_indices

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [32]:
y = np.array([0] * 5 + [1] * 5)
print "target names :", y
print "target objects :", X
print "paired target", zip(X,y)

skf = model_selection.StratifiedKFold(n_splits = 2, shuffle = True, random_state = 0)
for train_indices, test_indices in skf.split(X, y):
    print train_indices, test_indices

 target names : [0 0 0 0 0 1 1 1 1 1]
target objects : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
paired target [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1)]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [33]:
target = np.array([0, 1] * 5)
print target

skf = model_selection.StratifiedKFold(n_splits = 2,shuffle = True)
for train_indices, test_indices in skf.split(X, target):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[0 4 5 9] [1 2 3 6 7 8]
[1 2 3 6 7 8] [0 4 5 9]


#### ShuffleSplit

In [34]:
ss = model_selection.ShuffleSplit(n_splits = 10, test_size = 0.2)

for train_indices, test_indices in ss.split(X):
    print train_indices, test_indices

[3 0 2 5 4 7 6 9] [8 1]
[7 0 3 9 1 8 2 4] [5 6]
[2 6 1 7 0 3 5 9] [4 8]
[3 0 6 1 8 4 7 2] [9 5]
[7 2 9 8 3 1 0 5] [4 6]
[4 9 8 5 2 0 3 6] [1 7]
[0 1 7 9 4 2 3 8] [6 5]
[2 3 7 4 5 1 9 6] [8 0]
[1 5 8 7 0 2 3 4] [9 6]
[1 3 2 4 7 0 6 5] [8 9]


#### StratifiedShuffleSplit

In [35]:
target = np.array([0] * 5 + [1] * 5)
print target

sss = model_selection.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2)
for train_indices, test_indices in sss.split(X, target):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[7 8 9 0 4 2 5 1] [3 6]
[3 5 6 2 7 4 9 1] [0 8]
[7 4 0 6 5 3 8 1] [2 9]
[6 9 0 4 7 2 1 8] [3 5]


#### Leave-One-Out

In [36]:
loo = model_selection.LeaveOneOut()

for train_indices, test_index in loo.split(X):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators