In [1]:
import numpy as np

In [10]:
lst = [1,2,3,4,5,6,7,8,9,10]
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print type(arr), arr

<type 'numpy.ndarray'> [ 1  2  3  4  5  6  7  8  9 10]


In [7]:
arr[0:3]

array([1, 2, 3])

In [8]:
arr[[0,5]]

array([1, 6])

In [9]:
arr[ arr > 5]

array([ 6,  7,  8,  9, 10])

In [12]:
lst*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
print "Orig - ", arr
print "Mod - ", arr*2

Orig -  [ 1  2  3  4  5  6  7  8  9 10]
Mod -  [ 2  4  6  8 10 12 14 16 18 20]


In [17]:
print "Orig - ", arr
print "Mod - ", arr**2

Orig -  [ 1  2  3  4  5  6  7  8  9 10]
Mod -  [  1   4   9  16  25  36  49  64  81 100]


In [20]:
matrix = [[1,2,3],[4,5,6]]
matrix[0][0]

1

In [23]:
arr_2d = np.array(matrix)
arr_2d[1,2]

6

In [32]:
print "Rand (EQ) - ", np.random.random(3), "\n"
print "Rand (N) - \n", np.random.randn(3,3)

Rand (EQ) -  [0.86645369 0.31006266 0.76004135] 

Rand (N) - 
[[ 0.41538509  1.60381089  0.17985184]
 [ 0.44209026 -1.18178129 -0.38446152]
 [-0.65157851 -1.08976814 -0.17385128]]


In [39]:
np.arange(1,101)**2

array([    1,     4,     9,    16,    25,    36,    49,    64,    81,
         100,   121,   144,   169,   196,   225,   256,   289,   324,
         361,   400,   441,   484,   529,   576,   625,   676,   729,
         784,   841,   900,   961,  1024,  1089,  1156,  1225,  1296,
        1369,  1444,  1521,  1600,  1681,  1764,  1849,  1936,  2025,
        2116,  2209,  2304,  2401,  2500,  2601,  2704,  2809,  2916,
        3025,  3136,  3249,  3364,  3481,  3600,  3721,  3844,  3969,
        4096,  4225,  4356,  4489,  4624,  4761,  4900,  5041,  5184,
        5329,  5476,  5625,  5776,  5929,  6084,  6241,  6400,  6561,
        6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,  8100,
        8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
       10000])