In [1]:
import numpy as np

In [2]:
np.eye((4,5))

TypeError: 'tuple' object cannot be interpreted as an index

In [3]:
np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

ValueError: only 2 non-keyword arguments accepted

In [4]:
np.arange(1, 13, 2).reshape((3, 2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [5]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [6]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
a = np.eye(4, 5)
print(a)
print(a[ [0, 3], [1, 3]])

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
[0. 1.]


In [15]:
np.linalg.det(np.eye(3,3))

1.0

In [17]:
np.det(np.eye(5,5))

AttributeError: 'module' object has no attribute 'det'

In [18]:
np.linalg.eig(np.eye(3,3))

(array([1., 1., 1.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [19]:
np.eig(np.eye(5,5))

AttributeError: 'module' object has no attribute 'eig'