In [1]:
import numpy as np

In [4]:
a = np.array([1,2,2])
print "Norm:", np.linalg.norm(a,ord=2)

Norm: 3.0


In [5]:
b = np.array([3,3,3])
print "Distance", np.linalg.norm(b-a, ord=2)

Distance 2.449489742783178


In [6]:
from scipy.spatial.distance import cdist

In [10]:
print "Vector a dimmensions: ", a.shape
print "Vector b dimmensions: ", b.shape

Vector a dimmensions:  (3,)
Vector b dimmensions:  (3,)


In [12]:
a1 = a.reshape(1,3)
b1 = b.reshape(1,3)
print "Vector a dimmensions: ", a1.shape
print "Vector b dimmensions: ", b1.shape

Vector a dimmensions:  (1, 3)
Vector b dimmensions:  (1, 3)


In [14]:
print "Distance (prove): ", cdist(a1, b1, metric="euclidean")

 Distance (prove):  [[2.44948974]]


In [15]:
d = np.array([3, 0, 8, 9, -10])
print 'Вектор d:', d
print 'Его размерность:', d.shape

Вектор d: [  3   0   8   9 -10]
Его размерность: (5,)


In [16]:
print 'Вектор d с newaxis --> вектор-строка:\n', d[np.newaxis, :]
print 'Полученная размерность:', d[np.newaxis, :].shape

print 'Вектор d с newaxis --> вектор-столбец:\n', d[:, np.newaxis]
print 'Полученная размерность:', d[:, np.newaxis].shape

Вектор d с newaxis --> вектор-строка:
[[  3   0   8   9 -10]]
Полученная размерность: (1, 5)
Вектор d с newaxis --> вектор-столбец:
[[  3]
 [  0]
 [  8]
 [  9]
 [-10]]
Полученная размерность: (5, 1)


In [20]:
e = np.array([1,2,3])
print e[:, np.newaxis]

[[1]
 [2]
 [3]]


In [27]:
print "Vector A transposed: \n", a[np.newaxis, :]
print "Vector B transposed: \n", b[np.newaxis, :]
print "Distance between A and B computed: ", cdist(a[np.newaxis, :], b[np.newaxis, :], metric="euclidean")

Vector A transposed: 
[[1 2 2]]
Vector B transposed: 
[[3 3 3]]
Distance between A and B computed:  [[2.44948974]]


In [35]:
print "A: ", a
print "B: ", b
print "Scalar product A and B: ", np.dot(a,b)
print "Norm A: ", np.linalg.norm(a, ord=2)
print "Norm B: ", np.linalg.norm(b, ord=2)
print "Fngle between A and B: ", np.arccos(np.dot(a,b)/(np.linalg.norm(a, ord=2)*np.linalg.norm(b, ord=2)))

A:  [1 2 2]
B:  [3 3 3]
Scalar product A and B:  15
Norm A:  3.0
Norm B:  5.196152422706632
Fngle between A and B:  0.2756427992162655


In [38]:
print np.arange(1, 2, 0.3, dtype=float)

[1.  1.3 1.6 1.9]
